### ISSUE TITLE
Add the possibility of limiting the generation of credentials (X.509 certificates, username/password) to clients presenting tokens that satisfy certain conditions

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-dc/tts#182]
It should be possible to configure how the TTS authorizes the generation of credentials.
As an example, it could be useful to limit the generation of credentials only to clients presenting a token that:
- has a certain group linked to it, with the group specified in the configuration
- has been issued to a certain trusted client, with client id of the trusted client specified in the configuration

**Comment by bwegh** [comment]
this is closely linked to #177 as for this purpose parameter needs to be passed to the given plugin

**Comment by bwegh** [comment]
depends on #107 
else the work needs to be done twice

**Comment by bwegh** [comment]
how do you envision the configuration of this, @andreaceccanti ? do you have an idea?

**Comment by andreaceccanti** [comment]
Sorry for the belated answer, I must have missed the github notification on this. 

The plugin could have a list of group checks, so that it issues a credential only if the incoming token is linked to one of such groups. And the same for the client ids...

I don't know how TTS does configuration, but you could have for  a plugin an authorization
checks section that contains these kind of "policies", like
```
[authz_checks]
allowed_groups = ["groupa", "groupb",...]
allowed_client_ids = ["client_1", "client_2", ...]
```

I don't know if this is general enough though...

**Comment by bwegh** [comment]
I had the same feeling of it maybe not being general enough ...
```
allowed_groups = [ {'iss':'iam', 'groups':[ "groupa", "groupb"]}, 
                 {'iss':other, 'groups':[ 'grp', 'group']} ]

allowed_user = [ {'iss':'iam', 'user':[ "foo", "bar"]}, 
                 {'iss':other, 'user':[ 'peter']} ]
```

**Comment by andreaceccanti** [comment]
I would have a separate policy for each issuer instead of mixing issuers, especially since they could expose different attributes.

If you want to be really general you should give the possibility of defining an attribute matcher that would work with any attribute in the access token or in the user info response...
