### ISSUE TITLE
Footer text

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/tts#265]
Please update to:
This work was partially funded UROS the INDIGO DataCloud Project under grant agreement RIA 653549.

**Comment by bwegh** [comment]
@urost could you please check the spelling and update it, thanks

**Comment by urost** [comment]
OK, what should I update? All in tts? All the warnings, errors, etc.?

**Comment by bwegh** [comment]
@urost just the message above, wich will be the new footer of the web app, you mentioned it sounded 'germanish'

**Comment by bwegh** [comment]
I will copy/paste into the code :+1:

**Comment by urost** [comment]
Well, I guess it is OK the way it is, just remove UROS from it (why is it there in the first place, I'm a bit surprised  :)). So, like this:
This work was partially funded by the INDIGO DataCloud Project under grant agreement RIA 653549.

**Comment by bwegh** [comment]
okay, thanks, because "UROS" has been 'within' and I remembered that you mentioned that it sounded too german, so marcvs put the 'uros' there ;)

**Comment by urost** [comment]
Yep, I got that when I've checked the original sentence. (BTW, not sure if it sounds germanish, just "within" doesn't sound right,at least to me, but I don't think it's wrong..)

**Comment by bwegh** [comment]
PR is in the line ... I changed it to 'by' as you said :+1:
