### ISSUE TITLE
Text for greyed out options

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/tts#266]
Should be configurable for service
- default: Your authorisation is insufficient for this service. This may be due to missing group membership or due to a too low Level of Assurance (LoA) (Yes we already support that kind of stuff ;D)

- X.509: Your Level of Assurance (LoA) is probably too low to use this service. You will probably need to use a different service to log in (i.e. a different Identity Provider)

**Comment by bwegh** [comment]
introduced a setting called 'tooltip' to set the text to be displayed
