### ISSUE TITLE
TTS dockerization

### ISSUE THREAD

**Issue by marcocaberletti** [indigo-dc/tts#467]
Hi,
I'm trying to run WaTTS as Docker container, but I'm struggling with some things.
Inside the container, I install tts with RPM package (it's not a best practice, I know, but it's very easy), then I have the following problems.
- How to keep watts process in foreground? I've not found any options to add to the start command to do this.
- How to put log messages to standard output? I tried to create log files as symlink to /dev/stdout, but watts refuses to open and write on symlinks.
- How to monitor the container liveness and readiness? `watts ping` is a first step, but is there an health endpoint?

Thanks.

**Comment by bwegh** [comment]
Hello,

> How to keep watts process in foreground? I've not found any options to add to the start command 
> to do this.

Try using `watts console`

> How to put log messages to standard output? I tried to create log files as symlink to /dev/stdout, 
> but watts refuses to open and write on symlinks.

The above command should also solve that issue

> How to monitor the container liveness and readiness? watts ping is a first step, 
> but is there an health endpoint?

you can connect to the website or what do you mean? 
https://yourIP/api/v2/<name of a configured provider>/info returns some info including the version.

I hope that helps. I am not really good in Dockers, as I have no experience with it.
Yet I will create a Dockerfile to build a docker image.

**Comment by marcocaberletti** [comment]
Hi,
`watts console` works only if watts dies. I can try to use `watts attach-direct`, but I don't like the output format. I prefer the format used in log file, but it's not a big deal.

Thanks for the hints.

**Comment by bwegh** [comment]
I just added a directory with a Dockerfile, it does not work yet, but maybe you can help to make it work

https://github.com/indigo-dc/tts/tree/master/docker
