### ISSUE TITLE
random "500" internal server error

### ISSUE THREAD

**Issue by caifti** [indigo-dc/tts#552]
Hi,
from time to time, we experience the "500- internal server error" when trying to obtain x509 certificates.
I'm adding some debugging we did:

# openssl req -newkey rsa:1024 -keyout /var/lib/watts/simple_ca/users/private/userkey_4C.pem -sha256 -out /var/lib/watts/simple_ca/users/csr/userreq_4C.pem -subj /C=IT/O=CLOUD@CNAF/CN=a645351d-691c-4c25-9cfe-c78b2d6b3b9a@dodas-iam -passout file:/var/lib/watts/simple_ca/users/private/userpass_4C
Generating a 1024 bit RSA private key
.....++++++
.............++++++
writing new private key to '/var/lib/watts/simple_ca/users/private/userkey_4C.pem'
-----
# openssl ca -batch -config /var/lib/watts/simple_ca/users/private/userconf_4C -days 1 -policy policy_anything -extensions usr_cert -out /var/lib/watts/simple_ca/certs/usercert_4C.pem -passin file:/var/lib/watts/simple_ca/private/pass -infiles /var/lib/watts/simple_ca/users/csr/userreq_4C.pem
Using configuration from /var/lib/watts/simple_ca/users/private/userconf_4C
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
countryName           :PRINTABLE:'IT'
organizationName      :ASN.1 12:'CLOUD@CNAF'
commonName            :ASN.1 12:'a645351d-691c-4c25-9cfe-c78b2d6b3b9a@dodas-iam'
ERROR:Serial number 4C has already been issued,
      check the database/serial_file for corruption
The matching entry has the following details
Type          :Revoked
Was revoked on:180613073645Z
Expires on    :180613073645Z
Serial Number :4C
File name     :unknown
Subject Name  :/C=IT/O=CLOUD@CNAF/CN=0931b26e-89f6-4118-a5c4-dd7f9e9ec85a@dodas-iam

2019-06-04 09:08:48.698 [warning] <0.360.2>@watts:handle_credential_result:527 SESS<0.353.2> credential request for <<"x509">> failed: the sign failed: openssl ca -batch -config /var/lib/watts/simple_ca/users/private/userconf_0284 -days 7 -policy policy_anything -extensions usr_cert -out /var/lib/watts/simple_ca/certs/usercert_0284.pem -passin file:/var/lib/watts/simple_ca/private/pass -infiles /var/lib/watts/simple_ca/users/csr/userreq_0284.pem >> /var/lib/watts/simple_ca/users/private/userlog_0284 2>&1

# tail /var/lib/watts/simple_ca/users/private/userlog_0284
commonName            :ASN.1 12:'b7d0b0d0-999c-48f3-a717-ba129d1f57c5@dodas-iam'
ERROR:Serial number 0284 has already been issued,
     check the database/serial_file for corruption
The matching entry has the following details
Type          :Revoked
Was revoked on:190609200004Z
Expires on    :190609200004Z
Serial Number :0284
File name     :unknown
Subject Name  :/C=IT/O=CLOUD@CNAF/CN=0931b26e-89f6-4118-a5c4-dd7f9e9ec85a@dodas-iam

The "dirty" solution that we apply when something similar happens is: edit the /var/lib/watts/simple_ca/serial and increase the number written there.
For "some unknown reason" the automatic procedure that does this doesn't work.

**Comment by marcvs** [comment]
Which watts instance are you using?

**Comment by caifti** [comment]
Sorry for the delay - I'm talking about https://dodas-tts.cloud.cnaf.infn.it/

**Comment by marcvs** [comment]
Could this be some kind of race condition. WaTTS calls the plugins in parallel, if parallel requests come in. This could lead to such problems.

Since simple_ca is not really part of WaTTS, I can't support it with priority right now.  I'll contact you out-of-band for that.

**Comment by marcvs** [comment]
An alternative, is to try the go version of this plugin:
https://github.com/watts-kit/watts_plugin_x509

**Comment by caifti** [comment]
Hi Marcus,

the issue was there again today. 
Regarding the alternative solution - I'm sorry, I didn't use go until now so I don't understant the "deployment scheme", in the link above. Maybe you could be so kind to explain how to use it, or give me some references/bibliografy to read how to... go.

**Comment by marcvs** [comment]
Sure, the go version of the plugin you're using is here:
https://github.com/watts-kit/watts_plugin_x509
To install a new plugin, check the watts docs here:
https://indigo-dc.gitbook.io/token-translation-service
But in general copying the seeting of the simple_ca you're using in watts.conf should be a good start.
